# Generated by Django 5.1.2 on 2024-11-25 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_profile_old_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='old_cart',
            new_name='old_carty',
        ),
    ]
